apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.14/manifests/install.yaml
- ./ingress.yaml
patchesJson6902:
  - target:
      kind: Deployment
      version: v1
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/command
        value: ["argocd-server", "--insecure"]
  - target:
      kind: Service
      version: v1
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
